Repository SpaceyaTech/mastori-backend, pull requests merged in 2023-02, with the labels that each got.

#7 Add created_at & updated_at in Category model.
  blog/models.py
Labels: In progress

#9 Added comment model
  accounts/migrations/0001_initial.py
  accounts/migrations/0002_user_verification_code.py
  accounts/migrations/0003_alter_user_phone_number.py
  accounts/migrations/0004_alter_account_display_picture.py
  accounts/migrations/0004_alter_account_user.py
  accounts/migrations/0005_rename_name_account_account_name.py
  accounts/migrations/0006_alter_user_phone_number.py
  accounts/migrations/0007_alter_user_phone_number.py
  accounts/migrations/0008_alter_user_phone_number.py
  accounts/migrations/0009_alter_user_phone_number.py
  accounts/migrations/0010_alter_account_display_picture.py
  accounts/migrations/0011_merge_20221219_1042.py
  accounts/migrations/0011_merge_20230102_2059.py
  accounts/migrations/0012_merge_20230103_1021.py
  accounts/migrations/__init__.py
  accounts/models.py
  accounts/tests/test_models.py
  blog/admin.py
  blog/migrations/0001_initial.py
  blog/migrations/0002_alter_category_options.py
  blog/models.py
Labels: In review

#16 test comment model
  blog/tests/test_models.py
Labels: In review

#19 Reactions model
  blog/migrations/0005_remove_stori_published_date_alter_stori_status_and_more.py
  blog/models.py
Labels: In review

#22 Password validation
  CMS/settings.py
  accounts/serializers.py
  accounts/views.py
Labels: In progress, In review
